services:
  portfolio:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - YANDEX_TOKEN=y0__wgBENnOvJIEGMzDQSCLi6uxF3nqIc1SAqeyI1L_hI5LrJ2uM_Dyy0__wgBENnOvJIEGMzDQSCLi6uxF3nqIc1SAqeyI1L_hI5LrJ2uM_Dy
      - SITE_TITLE=ПОРТФОЛИО
      - SITE_AUTHOR=Никита Разумихин
      - ALBUM_PATHS=/Фото/Свадьба,/Фото/Природа
      # - UPLOAD_PASSWORD=секретный_пароль   # раскомментируй если нужна загрузка

      # Разделы: "Название:путь_на_диске" через запятую
      - SECTIONS=Концерты:/Portfolio, Разное:/Разные фотографии/портфолио/разные фотки

      # Теги под названием раздела (опционально)
      - SECTION_TAGS=Концерт:/Portfolio,

      # Текст в hero
      - HERO_DESCRIPTION=Репортажная фотография. Москва 

      # Контактный email в footer
      - CONTACT_EMAIL=razumihinnikita@gmail.com

      # Секция "О себе" (до 3 ячеек)
      - ABOUT_1_LABEL=Локация
      - ABOUT_1_VALUE=Москва
      
      - ABOUT_2_LABEL=Опыт
      - ABOUT_2_VALUE=3 года
      - ABOUT_2_SUB=Более 50 съёмок

      - ABOUT_3_LABEL=Контакт
      - ABOUT_3_VALUE=razumihinnikita@gmail.com
      